export const LOADING_ACTION = 'Loading Action';

export const SIGN_IN_USER_ACTION = 'Sign in user action';
export const SIGN_IN_USER_SUCCESS_ACTION = 'Sign in user success action';
export const SIGN_IN_USER_FAILURE_ACTION = 'Sign in user failure action';

export const SIGN_UP_USER_ACTION = 'Sign up user action';
export const SIGN_UP_USER_SUCCESS_ACTION = 'Sign up user success action';
export const SIGN_UP_USER_FAILURE_ACTION = 'Sign up user failure action';

export const SIGN_OUT_ACTION = 'SIGN_OUT_ACTION';
export const SIGN_OUT_SUCCESS_ACTION = 'SIGN_OUT_SUCCESS_ACTION';
export const SIGN_OUT_FAILURE_ACTION = 'SIGN_OUT_FAILURE_ACTION';

export const CREATE_NEW_LIST_ACTION = 'CREATE_NEW_LIST_ACTION';
export const CREATE_NEW_LIST_SUCCESS_ACTION = 'CREATE_NEW_LIST_SUCCESS_ACTION';
export const CREATE_NEW_LIST_FAILURE_ACTION = 'CREATE_NEW_LIST_FAILURE_ACTION';

export const DELETE_LIST_ACTION = 'DELETE_LIST_ACTION';
export const DELETE_LIST_SUCCESS_ACTION = 'DELETE_LIST_SUCCESS_ACTIONN';
export const DELETE_LIST_FAILURE_ACTION = 'DELETE_LIST_FAILURE_ACTION';

export const EDIT_LIST_ACTION = 'EDIT_LIST_ACTION';
export const EDIT_LIST_SUCCESS_ACTION = 'EDIT_LIST_SUCCESS_ACTION';
export const EDIT_LIST_FAILURE_ACTION = 'EDIT_LIST_FAILURE_ACTION';

export const ADD_NEW_POSITION_TO_LIST_ACTION = 'ADD_NEW_POSITION_TO_LIST_ACTION';
export const ADD_NEW_POSITION_TO_LIST_SUCCESS_ACTION = 'ADD_NEW_POSITION_TO_LIST_SUCCESS_ACTION';
export const ADD_NEW_POSITION_TO_LIST_FAILURE_ACTION = 'ADD_NEW_POSITION_TO_LIST_FAILURE_ACTION';

export const DELETE_POSITION_FROM_LIST_ACTION = 'DELETE_POSITION_FROM_LIST_ACTION';
export const DELETE_POSITION_FROM_LIST_SUCCESS_ACTION = 'DELETE_POSITION_FROM_LIST_SUCCESS_ACTION';
export const DELETE_POSITION_FROM_LIST_FAILURE_ACTION = 'DELETE_POSITION_FROM_LIST_FAILURE_ACTION';

export const GET_POSITIONS_FROM_LIST_ACTION = 'GET_POSITIONS_FROM_LIST_ACTION';
export const GET_POSITIONS_FROM_LIST_SUCCESS_ACTION = 'GET_POSITIONS_FROM_LIST_SUCCESS_ACTION';
export const GET_POSITIONS_FROM_LIST_FAILURE_ACTION = 'GET_POSITIONS_FROM_LIST_FAILURE_ACTION';

export const EDIT_POSITION_ON_LIST_ACTION = 'EDIT_POSITION_ON_LIST_ACTION';
export const EDIT_POSITION_ON_LIST_SUCCESS_ACTION = 'EDIT_POSITION_ON_LIST_SUCCESS_ACTION';
export const EDIT_POSITION_ON_LIST_FAILURE_ACTION = 'EDIT_POSITION_ON_LIST_FAILURE_ACTION';

export const GET_LIST_COLLECTION_ACTION = 'GET_LIST_COLLECTION_ACTION';
export const GET_LIST_COLLECTION_SUCCESS_ACTION = 'GET_LIST_COLLECTION_SUCCESS_ACTION';
export const GET_LIST_COLLECTION_FAILURE_ACTION = 'GET_LIST_COLLECTION_FAILURE_ACTION';

export const GET_CURRENT_LIST_ACTION = 'GET_CURRENT_LIST_ACTION';
export const GET_CURRENT_LIST_SUCCESS_ACTION = 'GET_CURRENT_LIST_SUCCESS_ACTION';
export const GET_CURRENT_LIST_FAILURE_ACTION = 'GET_CURRENT_LIST_FAILURE_ACTION';